version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
    container_name: app-container
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DBHOST: db
      DBUSERNAME: root
      DBPASSWORD: root
      DBNAME: blog
      DBPORT: 3306
      PORT: 3000

volumes:
  mysql-data:
